[package]
name = "unm_request"
description = "The request-related methods for UNM"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.6"
reqwest = { version = "0.11.10", features = [
    "json",
    "brotli",
    "deflate",
    "gzip",
    "native-tls-vendored",
    "socks",
] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
thiserror = "1.0.30"
url = "2.2.2"

[dev-dependencies]
once_cell = "1.10.0"
