[workspace]
members = [
    "unm_request",
    "unm_proxy_server",
    "unm_cli",
    "unm_providers",
    "unm_crypto",
    "unm_macro",
    "unm_utils",
]

[profile.release]
lto = true
codegen-units = 1
