[workspace]
members = [
    # "unm_resolver",
    # "unm_resolver_napi",

    "unm_test_utils",
    "unm_types",
    "unm_crypto",
    "unm_engine",
    "unm_request",
    "unm_selector",

    # Engines
    "unm_engine_bilibili"
]

[profile.release]
lto = true
