[package]
name = "unm_resolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.6"
once_cell = "1.9.0"
reqwest = { version = "0.11.8", features = ["json"] }
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["full"] }
url = "2.2.2"

[features]
