# The default context.
[context]
# The proxy URI to request services.
# Comment this line to disable Proxy feature.
# proxy_uri = ""

# Should we retrieve FLAC by default?
# enable_flac = false

# The search mode for waiting the response.
# Can be `fast_first` or `order_first`.
# search_mode = "fast_first"

# The default config for engines.
[context.config]
# "joox:cookie" = "..."

# Note that we don't allow users changing this value
# for the security concerns.
# "ytdl:exe" = "..."
