[package]
name = "unm_engine_kuwo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.53"
concat-string = "1.0.1"
http = "0.2.6"
log = "0.4.16"
random-string = "1.0.0"
reqwest = { version = "0.11.10", features = ["native-tls-vendored"] }
serde = { version = "1.0.136", features = ["derive"] }
unm_engine = { version = "0.1.0", path = "../../engine-base" }
unm_request = { version = "0.1.0", path = "../../request" }
unm_selector = { version = "0.1.0", path = "../../selector" }
unm_types = { version = "0.1.0", path = "../../types" }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
unm_test_utils = { path = "../../test-utils" }
