[package]
name = "unm_crypto"
description = "The crypto toolkit for UnblockNeteaseMusic."
version = "0.1.0"
edition = "2021"
repository = "https://github.com/UnblockNeteaseMusic/server-rust"
license = "LGPL-3.0-only"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }

thiserror = "1"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

regex = "1"
md5 = "0.7"
url = "2"
concat-string = "1.0.1"
faster-hex = "0.6.1"
base64 = "0.13.0"

[features]

