name: Build RESTful API binaries

on:
  push:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cargo-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-11
            target: x86_64-apple-darwin
          - os: macos-11
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
          target: ${{ matrix.target }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: v1-${{ matrix.os }}-${{ matrix.target }}-rest-api-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            v1-${{ matrix.os }}-${{ matrix.target }}-rest-api-cargo-build-${{ hashFiles('**/Cargo.lock') }}
            v1-${{ matrix.os }}-${{ matrix.target }}-rest-api-cargo-build-
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --release --bin unm_rest_api
      - uses: actions/upload-artifact@v2
        with:
          name: unm-rest-api-${{ matrix.os }}-${{ matrix.target }}
          path: |
            ./target/${{ matrix.target }}/release/unm_rest_api*
